services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env_files/env.prd
    networks:
      - proxy

  web:
    build: .
    restart: always
    command: uwsgi --ini /app/uwsgi.ini
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env_files/env.prd
    depends_on:
      - db
    networks:
      - proxy

  nginx:
    container_name: nginx
    image: nginx:1.22.1
    build: ./nginx
    restart: always
    volumes:
      - .:/app
    networks:
      - proxy
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=tomas.dev.br
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=tomas.dev.br
      - LETSENCRYPT_EMAIL=administrativo@tomas.dev.br

networks:
  proxy:
    external:
      name: nginx-proxy