services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env_files/env.dev